-- vim.api.nvim_create_autocmd("BufWritePost", {
-- 	pattern = { "*.html", "*.css", "*.js", "*.md", "*.ts", "*.liquid", "*.json", "*.yaml", "*.jsx", "*.tsx", "*.lua" },
-- 	command = "FormatWrite",
-- })
